---
- hosts: polybot
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker container image
      docker_image:
        name: "keretdodor/yolo5"
        source: pull

    - name: Run Docker container with environment variables
      docker_container:
        name: "yourapp"
        image: "keretdodor/yolo5"
        state: started
        restart_policy: always
        env:
          DYNAMODB_TABLE_NAME: "{{ dynamodb_table_name }}"
          SQS_QUEUE_URL: "{{ sqs_queue_url }}"
          S3_BUCKET: "{{ bucket_name }}"
          ALIAS_RECORD: "{{ alias_record }}"
          AWS_REGION: "{{ aws_region }}"

        
